import Link from 'next/link'

export default function HomePage() {
  return (
    <main className="min-h-screen flex items-center justify-center p-4 relative overflow-hidden">

      {/* Grid bg */}
      <div className="absolute inset-0 opacity-[0.04]"
        style={{
          backgroundImage: 'linear-gradient(var(--brand) 1px, transparent 1px), linear-gradient(90deg, var(--brand) 1px, transparent 1px)',
          backgroundSize: '60px 60px',
        }}
      />

      {/* Glow orb */}
      <div className="absolute top-1/3 left-1/2 -translate-x-1/2 -translate-y-1/2 w-[500px] h-[300px] rounded-full blur-[120px] opacity-10"
        style={{ background: 'radial-gradient(circle, var(--brand) 0%, transparent 70%)' }}
      />

      <div className="relative text-center space-y-8 animate-slide-up">

        {/* Badge */}
        <div className="inline-flex items-center gap-2 px-3 py-1.5 rounded-full border border-brand/20 bg-brand/5 text-xs font-mono text-brand">
          <span className="w-1.5 h-1.5 rounded-full bg-brand animate-pulse-brand" />
          Bitget AI Challenge · Kimi K2
        </div>

        {/* Logo */}
        <div>
          <h1 className="text-7xl font-display font-extrabold tracking-tight">
            <span className="text-brand text-glow-brand">Arbi</span>
            <span className="text-tx-primary">tex</span>
          </h1>
          <p className="mt-3 text-tx-secondary text-lg font-light max-w-md mx-auto leading-relaxed">
            AI-powered trading infrastructure.<br />
            Signals generated by Kimi K2. Executed on Bitget.
          </p>
        </div>

        {/* Features */}
        <div className="flex flex-wrap justify-center gap-3 text-xs font-mono">
          {['Live Market Data', 'AI Signal Generation', 'Automated Execution', 'Real-time WebSocket'].map((f) => (
            <span key={f} className="px-3 py-1.5 rounded-full bg-surface-card border border-surface-border text-tx-secondary">
              {f}
            </span>
          ))}
        </div>

        {/* CTA */}
        <div className="flex items-center justify-center gap-3">
          <Link
            href="/dashboard"
            className="px-6 py-3 bg-brand text-surface font-semibold rounded-xl hover:bg-brand/90 transition-all active:scale-[0.98] text-sm"
          >
            Open Dashboard →
          </Link>
          <Link
            href="/auth/login"
            className="px-6 py-3 border border-surface-border text-tx-secondary rounded-xl hover:border-surface-border-bright hover:text-tx-primary transition-all text-sm"
          >
            Sign In
          </Link>
        </div>

        <p className="text-xs font-mono text-tx-tertiary">
          Built with Next.js · Fastify · Supabase · Kimi K2
        </p>
      </div>
    </main>
  )
}
